# .github/workflows/update-minor-dependencies.yml
name: Update Minor Dependencies

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 3 AM UTC
  workflow_dispatch: # Manual trigger

permissions:
  contents: write # Required to create a pull request

env:
  NODE_VERSION: 'file' # Adjust if needed
  NCU_OPTIONS: '--target minor' # Options for npm-check-updates
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication

jobs:
  update-minor-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'file' # Adjust if needed
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Update Minor Dependencies
        run: |
          npx npm-check-updates -t minor -u || exit 1
          npm install

      - name: Check for Changes
        id: git-check
        run: |
          git add package.json package-lock.json
          git diff --cached --exit-code || echo "::set-output name=changes::true"

      - name: Delete Existing Branch
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git fetch origin
          git branch -D update-minor-dependencies || true
          git push origin --delete update-minor-dependencies || true
      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'chore: update minor dependencies'
          body: 'Automated minor dependency updates.'
          branch: update-minor-dependencies
          base: main
          labels: dependencies, automated-pr
          draft: false # Optional: Set to true if you want to create a draft PR
